site_name: UnixFilters
theme:
  name: material
  language: fr
  features:
    - content.code.copy

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Accueil: index.md
  - Getting started: getting_started.md
  - Guide:
      - Mise en place d'une tâche: help/init_task.md
      - Ajouter un bloc: help/add_block.md
      - Ajouter une commande: help/add_command.md
  - Documentation JavaScript: jsdoc/index.html
  - Documentation Checker: documentation_checker.md
