site_name: UnixFilters
theme:
  name: material
  language: fr
  # logo: assets/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep purple
      accent: purple

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: deep purple
      accent: purple
  features:
    - content.code.copy
    - navigation.top

plugins:
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes

nav:
  - Accueil: index.md
  - Getting started: getting_started.md
  - Librairie Blockly/JavaScript:
      - Documentation JavaScript: jsdoc/index.html
      - Guide:
          - Mise en place d'une tâche: help/init_task.md
          - Ajouter un bloc COMMANDE: help/add_command_block.md
          - Ajouter un bloc OPTION: help/add_option_block.md
          - Ajouter un bloc SYMBOLE: help/add_symbol_block.md
          - Ajouter un nouveau bloc: help/add_new_block.md
          - Créer une catégorie: help/create_category.md
          - Liste des blocs existants: help/list_blocks.md
  - Librairie Python:
      - Documentation Checker: documentation_checker.md
      - Guide:
          - Ajouter une commande: help/add_command.md
