site_name: UnixFilters
theme:
  name: material
  language: fr
  # logo: assets/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep purple
      accent: purple

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: deep purple
      accent: purple
  features:
    - content.code.copy
    - navigation.top

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Accueil: index.md
  - Getting started: getting_started.md
  - Guide:
      - Mise en place d'une tâche: help/init_task.md
      - Ajouter un bloc: help/add_block.md
      - Ajouter une commande: help/add_command.md
      - Créer une catégorie: help/create_category.md
  - Documentation JavaScript: jsdoc/index.html
  - Documentation Checker: documentation_checker.md
